STANDING = "STANDING"
LYING_X = "LYING_X"
LYING_Y = "LYING_Y"
SPLIT = "SPLIT"

NORMAL_ACTIONS = ["UP", "DOWN", "LEFT", "RIGHT"]
SPLIT_ACTIONS = ["UP", "DOWN", "LEFT", "RIGHT", "SWITCH_CUBE"]
ACTIONS = NORMAL_ACTIONS

VALID_MAP_CHARS = {"0", "1", "S", "G", "F", "B", "O", "X", "T"}
